version: '3'
services:
  api:
    image: team6/api
    ports:
      - "4557:4557"
    links:
      - mysql
      - arcus
      - nbase_arc
    environment:
      ARCUS_HOST: "team6"
      NBASE_ARC_HOST: "team6"

  mysql:
    image: "mysql:5.7"
    container_name: mysql-5.7
    volumes:
      - "db-data:/var/lib/mysql"
      - "./init/:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "team6"
      MYSQL_USER: "team6"
      MYSQL_PASSWORD: "team6"
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080

  nbase_arc:
    image: jkjh0819/ite3068:nbase-arc

  ngrinder-web:
    image: ngrinder/controller
    ports:
      - "16001:16001"
      - "12000-12009:12000-12009"
      - "8999:80"

  ngrinder-agent:
    image: ngrinder/agent
    links:
      - ngrinder-web
    environment:
      CONTROLLER_ADDR: "ngrinder-web:80"

volumes:
  db-data:
